name: Test
on:
  pull_request:
    branches: [1.x, main, beta]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Node v20
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Verify Plugin
        run: npm run verify

      - name: 'Lint'
        run: npm run lint && npm run prettier:check

      - name: Run tests
        run: npm run test:coverage:json

      - name: Update Coverage Badge
        id: update_badge
        run: |
          echo '📃 COVERAGE UPDATE: Updating the coverage badge...'
          changes=$(node ./scripts/update-readme-with-coverage-badge.js)
          if [ "$changes" == 'Updated the coverage badge' ]; then
            echo '📃 COVERAGE UPDATE: Successfully updated the coverage badge 🚀'
            echo "AFFECTED=true" >> $GITHUB_OUTPUT
          else
            echo '📃 COVERAGE UPDATE: No coverage changes, skipping readme updates'
            echo "AFFECTED=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.update_badge.outputs.AFFECTED == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "chore(docs): update coverage badge"
          git push
