name: Test
on:
  pull_request:
    branches: [1.x, main, beta]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install Node v20
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install deps
        run: npm ci

      - name: Check Types
        run: npm run typecheck

      - name: 'Lint'
        run: npm run lint && npm run prettier:check

      - name: Run Tests
        run: npm run coverage
